on:
  push:
    branches:
      - main

jobs:
  run-simulation:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1

    # install packages needed
    - name: install required packages
      run: Rscript -e 'install.packages(c("gtsummary", "remotes", "rmarkdown", "tidyverse"))'

    # render Rmd 
    - name: run-simulation
      run: Rscript -e 'rmarkdown::render("index.Rmd")'

    - name: Commit files
      run: |
        git config --global user.email "ghau@example.com"
        git config --global user.name "GitHub Actions User"
        git add --all
        git commit -am "gh-actions"
        git push